[project]
name = "nicegui-scaffold"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "nicegui>=3.4.1",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
]
